### ISSUE TITLE
error: prim_ops: Emulation chokes on zero dividend in idiv

### ISSUE THREAD

**Issue by PatrickRudolph** [wfeldt/libx86emu#23]
With a zero dividend the instruction "idiv %ebx" , with %ebx > 0  asserts a #DE instead of returning zero quotient and remainder.

**Comment by PatrickRudolph** [comment]
The corresponding C code is
```
long a = 0;
a = DIV_ROUND_CLOSEST(a, 1000);
```

**Comment by wfeldt** [comment]
I cannot see this. Do you have a machine code snippet where this shows?

**Comment by PatrickRudolph** [comment]
Analysing the register showed that the C code above is wrong, it's actually:

> -500 / 1000

The instruction is `0xf7fe` which is `idiv %esi`
The register dump in the exception handler shows:

EAX fffffe0c
EBX 00000000
ECX 00000000
EDX ffffffff
EIP 07f854ea
ESI 000003e8
EDI 07fa2e00

**Comment by wfeldt** [comment]
Oops, that's true. `idiv` and `imul` calculations have issues. I'll do a fix.

**Comment by wfeldt** [comment]
see https://github.com/wfeldt/libx86emu/pull/27

**Comment by PatrickRudolph** [comment]
Tested, works great! Thanks!
