### ISSUE TITLE
Hey libx86emu instruction stepping mode

### ISSUE THREAD

**Issue by fatrolls** [wfeldt/libx86emu#3]
Hey I don't know how to email you I wanted to ask you..

I may end up using your library for cpu emulation because it's very simple short and not too hard to understand others are way to complicated I need to add to this library floating-point instructions emulation to make it complete x86 emu emulator for my needs.

Now I just ask how do I step code line by line?.. I tried quickfix but EIP never changes?? how come.

I use this at the moment and EIP never changes and loop just crashes Segmentation fault error.

```
	//Set the emulator to start at this instruction. [EIP register]
	emu->x86.R_EIP = 0x00457D60; //start of function 0x457D60
	
	//Set the CPU emulator flags
	unsigned flags;
	flags = X86EMU_RUN_LOOP | X86EMU_RUN_NO_CODE;
	
        unsigned instructions_run_max = 1;
	if(instuctions_run_max) {
		emu->max_instr = instuctions_run_max; //max instructions to run
		flags |= X86EMU_RUN_MAX_INSTR;
	}
	
	//Run the CPU Emulator!
	while(emu->x86.R_EIP != 0x00458BD0) //where CPU emulator must stop address
	{
		x86emu_run(emu, flags);
        //I debug here line by line to see where CPU emulator needs more implmentation of new instructions.. I will try to put in floating-point operations myself using this.
	}
```

Have any way to step instructions line by line? not always running ```x86_emu_run(...);```

I look at it more in depth it looks like ```X86EMU_RUN_LOOP``` only detect JMP for EIP? ``` if(op1 == 0xeb)``` and ```else if(op1 == 0xe9)```  should detect every line?? i dont understand sorry.
But I really like your library

**Comment by demothorg** [comment]
**fatrolls**, I think you must increment `emu->max_instr` or zero `emu->x86.R_TSC`.
Something like this:
```
while(emu->x86.R_EIP != 0x00458BD0) //where CPU emulator must stop address
{
    x86emu_run(emu, flags);
    emu->max_instr++
}
```

**Comment by wfeldt** [comment]
I'll check.

**Comment by wfeldt** [comment]
demothorg is right, reset emu->x86.R_TSC after each x86emu_run()

X86EMU_RUN_LOOP checks for simple infinite loops (jumps to itself) to catch code people often use
to "stop" their program

**Comment by fatrolls** [comment]
thank you very much
