### ISSUE TITLE
Question about illegal opcode

### ISSUE THREAD

**Issue by blackbeaf** [wfeldt/libx86emu#33]
https://github.com/wfeldt/libx86emu/blob/0aed125dcc2214ccf9e1a52e9925ae654cefbaf1/ops.c#L5483

I'm looking for a emulator that can run on Win10 and then I found this. But this is only for linux. I plan to learn from this code to make a windows version but I found some opcode like 0x64,0x65 are marked as illegal , who can tell me why is that???

**Comment by wfeldt** [comment]
The op-code is a segment prefix and prefix decoding is handled directly when decoding the instruction.

There exist patches to make it compile on a Windows stack, see the open pull requests. But they weren't merged so far.

**Comment by blackbeaf** [comment]
@wfeldt   Understood. Thank you!!!!
