### ISSUE TITLE
Failed test when building on i686

### ISSUE THREAD

**Issue by meator** [wfeldt/libx86emu#38]
I have compiled libx86emu in a chrooted environment (my host was `x86_64` and the chrooted environment was `i686`). The `0032_rol16.init` test has failed. The logs are here: [0032_rol16.tar.gz](https://github.com/wfeldt/libx86emu/files/7355086/0032_rol16.tar.gz).
Does this mean that libx86emu shouldn't be used on i686?

**Comment by wfeldt** [comment]
No, this should work. Let me have a look.

**Comment by wfeldt** [comment]
Fixed with the linked pull request.

Thanks for reporting!

**Comment by meator** [comment]
Thanks!
