### ISSUE TITLE
Missing license file / notice

### ISSUE THREAD

**Issue by Conan-Kudo** [wfeldt/libx86emu#8]
According to the openSUSE spec, this is a 3-clause BSD licensed program. However, no `LICENSE` or `COPYING` file spells out the exact terms. Please correct this, as the BSD licenses require full notice and attribution.

**Comment by Conan-Kudo** [comment]
Without the proper terms in the project sources, I cannot package this for Fedora.

**Comment by wfeldt** [comment]
at last: https://github.com/wfeldt/libx86emu/pull/9
